name: Create Pull Request from develop to master

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout master branch
        run: git checkout master

      - name: Attempt to Merge develop into master
        run: |
          git merge develop --no-ff || echo "Merge conflict detected, creating a pull request."
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: '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'
          base: master
          head: develop
          title: 'Automatic Pull Request: Merge develop into master'
          body: |
            This pull request was created automatically because a merge conflict was detected when attempting to merge `develop` into `master`. Please review and resolve the conflicts.
