name: Merge Develop to Master

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop
          persist-credentials: true

      - name: Merge Master into Develop
        run: |
          git checkout develop
          git merge origin/master --no-ff

      - name: Checkout Master and merge Develop
        run: |
          git checkout master
          git merge develop --no-ff

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Push changes
        run: git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
