
name: Merge Develop to Master

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge Develop into Master
        uses: actions/checkout@v3
        with:
          ref: master
          persist-credentials: true

      - name: Merge Develop
        run: |
          git checkout develop
          git merge master --no-ff
          git checkout master
          git merge develop

      - name: Push changes
        run: git push origin master
