name: Merge develop to master

on:
  push:
    branches:
      - develop

jobs:
  merge-develop-to-master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout master branch
        run: git checkout master

      - name: Merge develop into master
        run: git merge develop --no-ff

      - name: Push changes to master
        run: git push origin master
        env:
          GITHUB_TOKEN: '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'
