name: Sync main to develop

on: 
  push: 
    branches:
      - main 

jobs: 
  branch-sync:
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4     
        with: 
          fetch-depth: 0 

      - name: Set up git 
        run: | 
          git config --global user.name 'Moustafa Elshafei'
          git config --global user.email 'moustafaelshafhy@gmail.com'     
          
      - name: Push changes to develop when main is updated
        if: github.ref == 'refs/heads/main' 
        run: | 
          git fetch origin 
          git checkout develop 
          git merge main -X theirs 
          git push origin develop
